rpgp/rpgp

- .gitignore
- pgp-ffi/Makefile
- pgp-ffi/rpgp.pc.in
This attempts to make the usual `make; make install` work.  In particular
it means people can invoke make install as sudo without having to worry
needing rust/cargo installed for the root user.
It needs to have a stab at knowing what the input files are sadly, and
also needs to create a single output; hence the, somewhat traditional,
build-stamp file.
It also uses some $(CURDIR) fun to so that `make -C pgp-ffi` will work
fine as well.
Lastly it fixes the librpgp.h typo and -lrpgp in the pkg-config file.
> Some Makefile voodoo

- pgp-ffi/Makefile
While I didn't realise Cargo.toml was generated I should really have
known better for the .h file.  Oh well.
Also obviously the -stamp file needs to be removed on clean.
> Do not depend on generated files, clean the stamp file

- src/base64_reader.rs
- src/line_reader.rs
Currently `LineBreak::seek` processes only `io::SeekFrom::Current(n)` and immediately converts `n` to its absolute value.
I test that forward and backward seek works as expected (currently it doesn't, hence draft PR).
> fix(line-reader): improve correctness of LineReader::seek

- src/composed/signed_key/key_parser_macros.rs
- src/packet/secret_key_macro.rs
- src/packet/signature/config.rs
- src/packet/signature/types.rs
Logs may be leaked accidentally and additional processing increases the
chance that this information will remain in memory.
Logging can be added as needed if required for debugging.
Related to #43
> fix: do not log sensitive information

- src/crypto/checksum.rs
- src/crypto/sym.rs
- src/errors.rs
Previously `checksum::sha1()` called `ensure_eq!` and the resulting error
propagated upwards.  As it can end up in the logs or UI, it is better
to make it more generic to avoid accidental information leaks.
Additionally, compute SHA1 in advance, before performing the checks.
In the future, these checks can be made constant time, even though it
is out of scope of rPGP threat model for now.
> feat: return the same error from decrypt_protected on invalid MDC

- src/packet/public_key_macro.rs
"EdDSA encryption" is not going to be implemented. ECDH case is already implemented.
Closes issue #66
> Clarify error message for EdDSA encryption

- src/composed/message/decrypt.rs
- src/composed/message/parser.rs
- src/composed/message/types.rs
- src/composed/signed_key/key_parser_macros.rs
- src/crypto/ecdh.rs
- src/crypto/sym.rs
- src/packet/many.rs
- src/packet/packet_sum.rs
- src/packet/secret_key_macro.rs
- src/packet/signature/config.rs
- src/packet/signature/de.rs
- src/packet/signature/ser.rs
- src/packet/signature/types.rs
- src/packet/user_attribute.rs
- src/types/packet.rs
- src/types/user.rs
This would greatly improve the logging in applications that are using rpgp.
Note that some of those message could even become trace!().
See issue #75.
> Turn info!() that are used for debugging/tracing into debug!()

- src/composed/signed_key/public.rs
- src/composed/signed_key/secret.rs
- src/composed/signed_key/shared.rs
I'm missing a "simple" API to get the expiration date of a key, much like the `expires` or `expired` output of gpg:
```
pub   rsa4096 2014-10-14 [SCEA] [expired: 2018-09-15]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
uid           [ expired] Test User <test@example.com>
```
> feat(key): add Signed(Public|Secret)Key::expires_at() method

- src/armor/reader.rs
- src/composed/key/builder.rs
- src/composed/key/mod.rs
- src/composed/message/types.rs
- src/composed/signed_key/mod.rs
- src/crypto/aes_kw.rs
- src/crypto/hash.rs
- src/errors.rs
- src/lib.rs
- src/packet/mod.rs
- src/types/key_id.rs
- tests/key_test.rs
- tests/message_test.rs
Goal: show basic usage in module docs
Ref #96
> docs: add a few doctests to showcase API usage 

- Cargo.toml
- src/crypto/eddsa.rs
Fixes #103.
Since `ed25519-dalek` moved to `v1.0.0-pre.4` (from `v1.0.0-pre.3`) approximately 15 hours ago, pgp no longer builds due to a change in the `ed25519-dalek` API.
The fix involves:
* Using the following now required traits in `src/crypto/eddsa.rs`: `signature::{Signature, Signer, Verifier}`
* Bringing in the signature crate as an explicit dependency (as this is where the above traits are exported)
> Required updates due to ed25519-dalek moving to v1.0.0-pre.4

- README.md
Android and Windows are the only platforms with 32 bits support for ARM and x86 being Windows fully 32 bits (x86_32) and in Android depending on the ISA. This is because of client framework limitations (Electron for desktop) and the state of some OS (iOS, Android, etc in their native platforms) but not the core itself.
> Fix ISA build versions specified

- src/composed/signature.rs
This is consistent with many other structs defined in rpgp, and it's
hard to do basic things such inspecting details of the signature
otherwise.
> Make signature field of StandaloneSignature public

- src/normalize_lines.rs
- src/packet/literal_data.rs
First commit adds a test revealing the bug.
Second commit fixes the problem by making `normalize_lines..rs` work on bytes instead of chars.
This simplifies the code and it should be faster as well.
> Fix corruption of non-ascii characters in text literals

- src/crypto/hash.rs
- src/packet/signature/config.rs
This makes it possible to skip intermediate buffers and simplifies the code.
The upstream `Digest` in rustcrypto also supports this, so there is precedent for doing it this way.
No functional change.
> Simplify code by making Hasher implement std::io::Write

- src/packet/public_key_macro.rs
Currently the only way to create a PublicKey is to have a pre-existing packet or to generate a new SecretKey and get it from there. This change adds a method that allows PublicKey objects to be synthesised from data from other sources, for example external key material.
> Add a method to construct a PublicKey from parameters.

- Cargo.toml
- src/composed/message/parser.rs
- src/composed/message/types.rs
- src/composed/signature.rs
- src/composed/signed_key/key_parser_macros.rs
- src/crypto/eddsa.rs
- src/crypto/hash.rs
- src/crypto/rsa.rs
- src/util.rs
std::convert::TryFrom is already used in src/line_reader.rs and has
been available since Rust 1.34:
https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html#tryfrom-and-tryinto
> Replace try_from dependency with std::convert::Try{From,Into}

- src/base64_decoder.rs
- src/packet/many.rs
- src/types/secret_key_repr.rs
&String can be compared with &str and &str satisfies the trait bounds
for std::fmt::builders::DebugStruct::field.
> Avoid some allocations via to_string

- src/crypto/hash.rs
I'm implementing cleartext signature verification using this crate
(I may contribute the code upstream once I have it working). A
problem I ran into is that as part of signature verification you
need to feed signature state into the hasher (which was already fed
the cleartext being verified). This means that you either need to
rehash the cleartext for each signature or maintain a per-signature
hasher. Both of these solutions are inefficient.
The hasher types used by this crate implement Clone. This means you
can have a single per-algorithm hasher then clone it before feeding
in signature state so you don't taint the hasher and can reuse it
for other signatures. However, because this crate's wrapper types
don't implement Clone, this optimization isn't available.
This commit implements …
> Derive Clone on hasher types

- Cargo.toml
Fixes #179 
This removes the non-standard requirement on zeroize, fixing ecosystem incompatibilities with rpgp.
> Fix zeroize version

- Cargo.toml
It removes dependency on `time` crate.
> Disable `oldtime` feature of `chrono`

- src/composed/message/types.rs
The argument is not transformed, so find is sufficient.
This change fixes a clippy error causing the CI to fail.
> Replace find_map with a find

- Cargo.toml
`clear_on_drop` seems to be completely replaced by `#[zeroize(drop)]`.
> Remove unused clear_on_drop dependency

- src/composed/key/builder.rs
The method `can_authenticate(bool)` was missing from the `SubkeyParams` builder but was supported by everything further down.  I have tested this by generating a key that has an authenticate subkey and using this to successfully log into a Linux server using SSH.
> feat: allow subkeys to be created with the authentication flag enabled

- src/crypto/sym.rs
Macros encrypt_regular and decrypt regular do not use the bs (block size) argument, drop it.
Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
> crypto/sym: drop unused block size arguments

- README.md
Hi!
This PR addresses three minor README points:
1. use `permissive` instead of `libre`
`Libre` is often associated with GNU and their [GPL licenses][0]. Avoid that wording and instead use `permissive` that immediately evokes [Apache and MIT licenses][1].
[0]: https://www.gnu.org/philosophy/free-sw.en.html
[1]: https://en.wikipedia.org/wiki/Permissive_software_license
2. Mention default Nettle for Sequoia
Sequoia can use [several different cryptographic backends besides Nettle][2] even though Nettle is configured as a default backend.
[2]: https://gitlab.com/sequoia-pgp/sequoia/-/blob/main/openpgp/README.md#crypto-backends
3. Use `pure Rust` instead of `full Rust`.
I think it's more idiomatic to say `pure Rust` while `full Rust` is not so straightforward.
(Full disclosure: I am paid by …
> Fix a couple of minor points in README

- src/packet/one_pass_signature.rs
We need to parse some specific members of an OnePassSignature, thus they need to be public
> Packet: make members of OnePassSignature public

- src/types/key_id.rs
- tests/key_test.rs
This allows formatting KeyId objects with `{:X}` and `{:x}` formatting specifiers.
> feat: Implement `LowerHex` and `UpperHex` for `KeyId`

- src/crypto/checksum.rs
- src/crypto/sym.rs
- src/lib.rs
- src/types/params/plain_secret.rs
When decrypting large files, the `data` used in the `sym::SymmetricKeyAlgorithm::decrypt_protected` method would be copied via the `concat` used when taking the checksum.
This change updates the function to avoid the copy, by iterating over the relevant parts of the checksum as immutable references. This should be "transparent" to the overall api of the lib so I thought it might make a nice change.
I am using `gpg` to create large filesystem updates (basically, `.ext4.gpg`) that can be several hundred MB in size, destined for embedded machines with only several hundred MB of RAM. On those machines, I am using this library in my application to decrypt the updates and apply them. Currently, I am running out of memory during the process.
I did some testing to verify that `concat` does indeed …
> perf: avoid `concat` in sha1 checksum impl

- src/packet/signature/de.rs
- src/packet/signature/ser.rs
- src/packet/signature/types.rs
Currently, when reading a revocation signature with an unknown "revocation code" value, the "revocation code" field is dropped during parsing, so it's missing from the resulting `Signature` struct. As a result, `Signature::verify_key()`  considers the cryptographic signature to be wrong.
So applications have to assume such a revocation is "fake", and ignore it, because the self-signature is broken. In such a case, applications will ignore a legitimately self-signed revocation, just because the "revocation code" field contains an unexpected value. This seems like an unfortunate failure mode.
This PR implements parsing (and serialization) for any u8 value in the code field.
If there is a better way to implement this, I'd be happy about pointers, and to improve this PR.
> Handle other RevocationCode values

- src/composed/message/types.rs
This change makes it harder for users of the API to mistakenly think they have successfully validated a message, when in fact they have used the API wrong.
> fix: return an error in Message::verify if we don't know what to verify

- src/armor/reader.rs
I initially added this `ignore` as a commit in #271.
But now think it might be good to push this to main right away (other PRs keep showing this false positive)
> ignore clippy false positive

- README.md
I've noticed that the image shows "build failing" but the CI succeeds and works (as evidenced by clicking the link) so I went to Actions and pressed "Create status badge" and replaced the link below with what was suggested by GitHub.
Edit: I've noticed the Rust version badge was also out of date so I've fixed that too to reflect what is written as text.
> Fix CI status image

- src/composed/key/builder.rs
- src/types/mpi.rs
- src/types/params/plain_secret.rs
I've broken out the MPI padding-related part of #304.
I believe this fixes cases where the secret key MPI starts with a zero byte, but very much invite scrutiny.
For testing, I increased the number of rounds in `key_gen_ecdsa_p256` to include the first test case where the generated secret key has a leading zero byte. Without the changes in this PR, that test fails.
> fix(ecdsa): don't pad ecdsa secret MPIs

- src/crypto/ecdh.rs
Padding in https://www.rfc-editor.org/rfc/rfc6637 is described as being based on PKCS5. However, RFC 6337 allows padding that exceeds the size of one block, with the goal of obfuscating the size of the symmetric key material.
This commit changes the default size of padded payloads to 40 bytes, which is the regular size of a padded payload that contains a AES256 key.
fixes #292
> feat: obfuscate symmetric key length with ecdh padding

- src/composed/shared.rs
- src/composed/signed_key/parse.rs
- src/types/s2k.rs
A possible approach to autodetecting armored vs. binary OpenPGP streams.
Whatever approach we take, we should implement it for all types of data: keys, messages and raw signatures.
But I wanted to solicit thoughts, first.
> Detect armor

- src/composed/message/types.rs
- src/packet/mod.rs
- src/packet/sym_encrypted_protected_data.rs
I don't think making `SymEncryptedProtectedData::data` pub is right, but `::data()` is already taken (and it doesn't return that field).
We probably want to shuffle this namespace around, some. Do you have an idea/preference?
Maybe `SymEncryptedProtectedData::data()` should be renamed to `::data_as_slice()` or something like that?
> add pgp::packet::sym_encrypted_protected_data::Data to the public API

- Cargo.toml
- src/crypto/ecdh.rs
- tests/backward-compat.rs
this style of padding is compatible with older rpgp versions (long padding can only be read in v0.11.0 and newer, via #280).
this commit effectively undoes #307.
> revert to producing short padding for ecdh.

- src/packet/signature/config.rs
- src/packet/signature/types.rs
Hashers from RustCrypto implement `std::io::Write` and making use of that trait in the `hash_signature_data` makes it possible to use other hashers which do not implement RustCrypto Hasher trait.
Additionally it allows using hashers which may fail during the digest update (such as OpenSSL hashers).
(just for the context I'm using this in my [hasher-test](https://github.com/wiktor-k/hasher-test?tab=readme-ov-file#hasher-test) repository and the hasher I'm passing happens to be from a new `-pre` version of Rust Crypto's sha2 crate. Due to versioning for Rust it's not the same Hasher trait but the same Write trait).
> feat: Make `SignatureConfig::hash_signature_data` more flexible

- src/packet/many.rs
If the submodule hasn't been cloned, then test_many_parsers will also fail, so ignore this failing test like the other ones that depend on the sks dump.
> Ignore another sks-dump test failure

- src/crypto/ecdh.rs
- src/crypto/ecdsa.rs
- src/crypto/eddsa.rs
- src/crypto/rsa.rs
- src/packet/key/secret.rs
- src/types/mpi.rs
- src/util.rs
- tests/hsm-test.rs
- tests/key_test.rs
This is the same as #410, but rebased onto current main
> fix: Remove the unchecked Mpi constructor (and other Mpi tweaking)

- src/util.rs
Current implementation is wrong, it should have be `bytes.remove(0)`.
But removing each byte individually is sub optimal. The method `drain()` does the hard work instead.
> fix: make strip_leading_zeros_vec() work correctly

- src/util.rs
- Looks like that is a typo left over from migrating `nom` to v7.
- Before migration, this was `alt!(input, eof!() | eol)`. 
- The migrated one looks wrongly (recursion eof).
- But anyway, this function is used nowhere, so remove it.
> chore: remove unused and erratic end_of_line() fn

- src/armor/reader.rs
This patch makes the `Display` implementation directly write static strings to the formatter instead of first allocating a `String` object. Call-sites have also been adjusted to take advantage of the formatter.
The `to_string` function is automatically attached by a `ToString` blanket implementation.
> chore: Optimize `Display` implementation for `BlockType`

- Cargo.toml
Following up on https://github.com/rpgp/rpgp/pull/397#issuecomment-2378096286 :
The rationale for https://github.com/rpgp/rpgp/pull/397 only mentioned needing the _option_ of older dependencies to build for Debian using Debian-packaged Rust libraries.  It didn't mention any reason to _force_ downgrades e.g. to improve security or stability or address a bug.
This PR relaxes those dependency requirements to avoid unnecessary dependency downgrades relative to `pgp` 0.13.2 for projects building with crates directly from crates.io.
Tests and stress tests pass locally, and `cargo deny` is ok locally.
> Relax dependencies

- deny.toml
That license doesn't seem to be needed anymore, and `cargo deny` complains about its unnecessary presence
> ci: drop "Unicode-DFS-2016" from allowed licenses

- src/types/key_id.rs
While `KeyId`s are mostly terrible and a legacy format, it can unfortunately still be useful to use them e.g. as keys in Maps, in weird edge cases.
> feat: derive Hash for KeyId

- src/composed/signed_key/shared.rs
- tests/hsm-test.rs
- tests/key_test.rs
- tests/rfc9580.rs
This is less dangerous than checking
`is_public()` or `is_secret()`
and then using `into_secret()` and `into_public()` that may panic.
> feat: implement TryFrom<PublicOrSecret> for Signed{Public,Secret}Key

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/composed/key/builder.rs
- src/crypto/mod.rs
- src/packet/key/public.rs
- src/packet/key/secret.rs
- src/packet/public_key_encrypted_session_key.rs
- src/packet/public_key_parser.rs
- src/types/params/plain_secret.rs
- src/types/params/public.rs
- src/types/secret_key_repr.rs
- tests/rfc9580.rs
- tests/security.rs
- `x448` support is now disabled by default and gated behind a feature flag `unstable-curve448`
> feat!: implement feature gate for x448

- src/types/mpi.rs
- tests/key_test.rs
I found the naming a bit confusing, and the casting seems needlessly complicated too (?).
Also, i think the comparison with MAX_EXTERN_MPI_BITS was wrong (it compared bytes against bits), so the limit was ineffective.
> mpi minor cleanup

- src/composed/message/types.rs
Sorry for small PR, but I think it would be useful to add explanation as to what is SEIPDv1 and why you might want to use it as after upgrading from 0.13 it took me some time to find out
> Add note on compatibility reasons to use seipdv1

- README.md
- src/lib.rs
This change makes the README be part of the root crate docs.
The main benefit is that all Rust code examples will be included by `cargo test` (I've marked them `no_run` since they use non-existent files, but I think they could be adjusted to read from sample keys).
> doc: Include crate README in docs for automatic example validation

- .github/workflows/ci.yml
- .gitmodules
Currently, using a pre-release git dependency in Cargo.toml makes cargo pull the tests directory as well which results in gigantic, unnecessary traffic.
```toml
[dependencies]
pgp = { git = "https://github.com/rpgp/rpgp" }
```
This patch disables pulling the tests by default and makes cargo skip the submodule:
```sh
$ cargo build
Updating git repository `https://github.com/rpgp/rpgp`
Skipping git submodule `https://github.com/rpgp/tests.git` due to update strategy in .gitmodules
```
See: https://github.com/rust-lang/cargo/issues/4247#issuecomment-1149178736
> build: Make `cargo` not pull the tests submodule when referencing rpgp via git

- src/composed/message/reader/limited.rs
- src/composed/message/reader/packet_body.rs
- tests/message_test.rs
This is tested in the interop suite for the final fixed chunk in partial encoded bodies.
> fix: check that fixed part is as long as it claims to be

- src/composed/message/types.rs
We should probably not decrypt SED packets by default.
But I'm not sure how best to expose this in the API. Thoughts welcome.
> guardrails against sed packet decryption

- src/composed/cleartext.rs
The current implementation of `dash_unescape_and_trim` doesn't correctly handle empty but dash-escaped lines:
It first strips trailing spaces, after which it can't un-dash-escape such lines anymore, because they start with only a single dash (and not with a dash and a space anymore).
So trailing whitespace must be removed *after* un-dash-escaping.
This PR implements that order of operations.
> fix: handle empty dash-escaped lines in CSF

- src/types/params/public/ecdh.rs
- src/types/params/public/ecdsa.rs
This aligns the EcdsaPublicParams API with EcdhPublicParams
> feat: add EcdsaPublicParams::curve and is_supported

- src/adapter/ecdsa.rs
- src/adapter/rsa.rs
This is useful for building a `pgp::composed::SignedPublicKey` from an HSM-backed signer.
```rust
let pgp_signer = pgp::adapter::RsaSigner::new(sync_signer, KeyVersion::V4, chrono::Utc::now())
.unwrap();
let details = pgp::composed::KeyDetails::new(
Some(user_id),
Default::default(),
Default::default(),
keyflags,
Default::default(),
Default::default(),
Default::default(),
Default::default(),
Default::default(),
);
let signed_public_key =
pgp::composed::PublicKey::new(pgp_signer.public_key().clone(), details, vec![])
.sign(
&mut rng,
&pgp_signer,
pgp_signer.public_key(),
&Password::empty(),
)
.unwrap();
```
> signer: expose the public key

- src/composed/cleartext.rs
- src/composed/signed_key.rs
- src/packet.rs
- src/packet/key/public.rs
- src/packet/key/secret.rs
- src/packet/user_attribute.rs
- src/packet/user_id.rs
Fixes #605
Historically, signatures have signaled the issuing key with the (Key ID-based) "Issuer" subpacket.
More recently, the (newer and Fingerprint-based) "Issuer Fingerprint" subpacket has been added to OpenPGP.
In RFC 9580, generation of the "Issuer Fingerprint" subpacket is a "SHOULD:
> "The OpenPGP Key fingerprint of the key issuing the signature. This subpacket SHOULD be included in all signatures."
See: https://www.rfc-editor.org/rfc/rfc9580.html#issuer-fingerprint-subpacket
> fix: always produce IssuerFingerprint subpacket for signatures

- src/composed/message/parser.rs
- src/composed/message/reader/signed_one_pass.rs
- src/composed/message/types.rs
- src/packet/one_pass_signature.rs
Refuse to validate one pass signed messages if the metadata in the One Pass Signature packet doesn't match the corresponding metadata in the Signature packet.
(Also see this thread for some more discussion of this topic: https://mailarchive.ietf.org/arch/msg/openpgp/RLMBugGhg_c9xT7zmDrkBklRZB8/)
> fix: if one pass sig metadata doesn't match signature, don't validate

- src/types/params/public/dsa.rs
- tests/key_test.rs
Fuzz testing produced some test cases where excessively long DSA parameters caused slow runs.
This PR limits the length of DSA public parameters based on https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf
> fix: limit length of DSA public parameters

- README.md
- docs/SECURITY_STATUS.md
- docs/openpgp.md
In the [2024 ROS security evaluation](https://github.com/rpgp/rpgp/blob/main/docs/SECURITY_STATUS.md#2024-12), the "Non-Findings" sections suggest a number of improvements to the documentation.
This PR addresses these pointers.
> docs: changes based on 2024 ROS input
