rpgp/rpgp

Cargo.toml, src/armor.rs, src/composed/key.rs, src/lib.rs, src/packet/single.rs, src/packet/tags/privkey.rs, src/packet/tags/pubkey.rs, src/packet/tags/sig.rs, src/packet/types/key.rs, src/util.rs
I have added test outlines, but am unsure of how you would like the tests to be structured. These functions should apply to both a whole parsed key, but also apply to subkeys.
I tested only with DSA and RSA on V3 and V4, and *should* be correct for other algorithms.
=> Add fingerprint() and key_id() method

.circleci/config.yml, .gitmodules, README.md, appveyor.yml, pgp-ffi/Cargo.toml, src/packet/many.rs, tests/key_test.rs
=> Split tests

src/packet/many.rs, src/packet/single.rs
=> Incomplete

.circleci/config.yml, src/armor/reader.rs, src/base64_decoder.rs, src/base64_reader.rs, src/line_reader.rs
=> fix: make armor parsing more resilient

src/packet/literal_data.rs
=> fix(packet): correct string creation for LiteralData::to_string

README.md
=> docs(readme): updates to reflect current status better

Cargo.toml, src/crypto/aead.rs, src/crypto/ecdh.rs, src/crypto/eddsa.rs, src/crypto/hash.rs, src/crypto/rsa.rs, src/crypto/sym.rs, src/packet/public_key_macro.rs, src/packet/secret_key_macro.rs, src/packet/single.rs, src/types/mpi.rs, src/types/params/plain_secret.rs, src/types/params/public.rs, src/types/params/secret.rs, src/types/secret_key_repr.rs, src/util.rs
=> feat: zero out memory for secret key structures

src/composed/message/types.rs, src/crypto/ecdh.rs, src/packet/public_key_encrypted_session_key.rs
<del>Ported test by @r10s from https://github.com/deltachat/deltachat-core-rust/pull/1316</del>
Description of bug and bugfix is in commit messages. Do not squash.
=> Fix ECDH serialization for encrypted session keys with leading zeros

Cargo.toml, src/base64_decoder.rs, src/packet/many.rs, src/util.rs
This did not help in perf much and creates more issues than needed
when cross compiling
=> fix: remove usage of slice_deque

src/composed/message/types.rs, src/packet/signature/config.rs, src/packet/signature/types.rs
=> feat: make sign/verify utilize trait std::io::Read

Cargo.toml
Blocked on https://github.com/RustCrypto/stream-ciphers/issues/163
=> update crypto deps

README.md
questions like that pop up here and there, most recently in #114
closes #114
nb: another difference: rpgp is easier to type than sequoia :D
=> document key differences between rPGP and Sequoia

Cargo.toml
=> Upgrade pretty_assertions to 1

README.md
I think it makes it less ambiguous
=> Add comma in `README` for clearer message

src/armor/reader.rs, src/packet/public_key_parser.rs, src/packet/signature/de.rs, src/packet/single.rs, src/packet/sym_key_encrypted_session_key.rs
it appears I missed some things during cleanup of #214
- some comments were accidentally removed (fixed in 64f957b443a9a318bd71fd662b37a39dd2955cc0)
- a section that could use a simpler parser combinator (fixed in 0bbac97d0893453211f8f666e7f08c404dd99e2c)
- some places unecessarily chained parsers manually (fixed in 8d557d5976d0f5278bc32cfc7c8c7388de5c247b)
=> followup to #214

Cargo.toml, src/armor/reader.rs, src/base64_decoder.rs, src/packet/many.rs
=> refactor: switch from buf_redux to buffer-redux

README.md
fix #226 by linking to published security audit
=> mention the security audit 

CHANGELOG.md, src/composed/key/builder.rs, src/crypto/ecdsa.rs, src/packet/public_key_parser.rs, src/packet/signature/config.rs, src/packet/signature/types.rs, src/types/params/plain_secret.rs, src/types/params/public.rs, tests/key_test.rs
=> fix: signature issues

Cargo.toml, src/composed/key/builder.rs, src/crypto/rsa.rs, tests/key_test.rs
=> fix: update to released rsa@0.9.0

.github/workflows/ci.yml
=> Fix CI, remove broken platforms

src/packet/signature/types.rs
When verifying a *Primary Key Binding Signature* (see https://www.rfc-editor.org/rfc/rfc4880.html#section-5.2.1) [informally called a "back signature"], the two keys that get hashed must be hashed in reverse order, relative to what `Signature::verify_key_binding` does.
The reason for the inverse hashing order is that the RFC keeps a stable order of "primary first, subkey second" when hashing. However, for the "back signature", the roles of signer and signee are swapped.
This PR adds a second key binding verification function ("verify_backwards_key_binding") that hashes the keys in the correct order for back signatures.
=> add Signature::verify_key_binding_primary_back_sig

.github/workflows/ci.yml, Cargo.toml
This nightly version avoids triggering the errors from https://github.com/dalek-cryptography/curve25519-dalek/issues/618
=> chore: use a variable for "nightly", use a fixed nightly version for now

src/packet/signature/config.rs, src/packet/signature/types.rs
It's unsafe for consumers to rely on data from an unhashed subpacket as though it were self-signed by the certificate owner. Applications that need to interpret data from an unhashed subpacket should opt in to this using explicit code.
=> fix: Don't return unhashed subpackets in `subpackets()`

src/composed/message/decrypt.rs, src/composed/message/parser.rs, src/composed/message/types.rs, src/crypto/ecdh.rs, tests/message_test.rs
A suggested approach to fix #298
=> A Message::Encrypted should contain exactly one Edata

src/packet/many.rs
=> fix(packet-parser): increase buffer size for unknown size

Cargo.toml
=> chore: set debug in Cargo.toml to the normalized value

README.md, docs/SECURITY_STATUS.md
also adding two more projects, discovered from https://crates.io/crates/pgp/reverse_dependencies
=> small refinements/typo-fixes

README.md
The example in README.md is incorrect, I attempted to fix it.
=> Fix the example in README.md

README.md
I think the verification example might slightly more intuitive without handling private keys in it? (usually, signatures are verified by third parties without access to the private key material)
Also, I wondered if having more human-friendly "data" in the second example would be a bit easier to grok for readers?
(Cc: @jonas089)
=> README: some more example adjustments

src/packet/signature/config.rs
=> fix: remove stray eprintln

Cargo.toml, src/base64_decoder.rs, src/composed/message/decrypt.rs, src/crypto/dsa.rs, src/crypto/ecdh.rs, src/crypto/ecdsa.rs, src/crypto/eddsa.rs, src/crypto/rsa.rs, src/de.rs, src/lib.rs, src/packet/compressed_data.rs, src/packet/literal_data.rs, src/packet/mod_detection_code.rs, src/packet/padding.rs, src/packet/signature/config.rs, src/packet/signature/de.rs, src/packet/signature/types.rs, src/packet/single.rs, src/packet/sym_encrypted_data.rs, src/packet/sym_encrypted_protected_data.rs, src/packet/sym_key_encrypted_session_key.rs, src/packet/user_attribute.rs, src/types/key_id.rs, src/types/mpi.rs, src/types/params/encrypted_secret.rs, src/types/params/plain_secret.rs, src/types/params/public.rs, src/types/revocation_key.rs, src/types/s2k.rs
=> refactor: remove unused Deserialize trait

src/packet/key/secret.rs
API sketch for changing secret key packet locking
=> feat(secret_key_macros): impl set_password and set_password_and_s2k

benches/benchmarks/key.rs, benches/benchmarks/message.rs, src/composed/key/builder.rs, src/composed/key/public.rs, src/composed/signed_key/public.rs, src/composed/signed_key/secret.rs, src/crypto/ecc_curve.rs, src/crypto/eddsa.rs, src/crypto/public_key.rs, src/packet/key/public.rs, src/packet/key/secret.rs, src/packet/public_key_parser.rs, src/packet/signature/config.rs, src/packet/signature/de.rs, src/packet/signature/types.rs, src/packet/user_id.rs, src/types/params/plain_secret.rs, src/types/params/public.rs, src/types/public_key.rs, tests/hsm-test.rs
This reflects a naming change in RFC 9580
=> refactor: groundwork for v6 implementation

src/packet/single.rs
=> Add special error message for packet 20

src/crypto/ecdh.rs
oops. this mistake confused me today.
=> fix: parameter name

src/composed/key/builder.rs, src/composed/message/types.rs
These are only used for debugging anyway.
Closes #403
=> test: skip writing files by default

src/util.rs
Having two functions, one called `something_length()` and the other `something_len()` looks strange to me.
Suggest to merge the two; the second one was not referenced from other parts anyway, and the merged function should be easier to understand, hopefully.
=> refactor: merge write_packet_len into write_packet_length

src/composed/message/types.rs
See https://github.com/rpgp/rpgp/issues/430
Closes: #430
=> Avoid writing to the crate source unnecessarily during tests

src/armor/reader.rs, src/composed/any.rs, src/composed/cleartext.rs, src/lib.rs, src/packet/many.rs
Based on https://github.com/rpgp/rpgp/pull/428
Closes https://github.com/rpgp/rpgp/issues/352
=> fix: correctly deal with multi buffer reads in dearmoring

.github/workflows/ci.yml, Cargo.toml, benches/benchmarks/key.rs, benches/benchmarks/message.rs, benches/benchmarks/mod.rs, benches/benchmarks/s2k.rs, src/composed/key/builder.rs, src/composed/message/types.rs, src/crypto/ecdh.rs, src/errors.rs, src/lib.rs, src/types/s2k.rs, tests/key_test.rs
- `nightly` wasn't having any real benefit anymore
- `gperftools` is not really used anymore to profile
- ignore some slow tests to speed up CI
- improve over all CI times
=> refactor: remove unused feature flags and improve CI runtime

Cargo.toml
- bitfield@0.17
- thiserror@2.0
=> feat: update deps, bitfield and thiserror

src/crypto/aead.rs, src/crypto/hash.rs, src/crypto/public_key.rs, src/crypto/sym.rs, src/types/compression.rs, src/types/packet.rs
=> make algorithm enums non-exhaustive

src/composed/any.rs, src/composed/message/builder.rs, src/composed/message/parser.rs, src/composed/message/types.rs, src/crypto/hash.rs, src/packet/signature/config.rs, src/packet/signature/types.rs, src/types/password.rs, src/util.rs
this is needed to allow working in an async environment, like deltachat does
=> fix: enforce Send for Message

src/composed/message/builder.rs
We might want to DRY this code, but I wanted to sketch an API to deal with #507, to discuss
=> feat: add encrypt_to_key_anonymous functions

src/composed/message/builder.rs, src/composed/message/types.rs, src/types/params/public/ed25519.rs
partial fix of the complaints of `cargo doc`
=> happier cargo doc

src/crypto/aead/decryptor.rs
Before
- Seipdv2 decryption: `275 MB/s`
After
- Seipdv2 decryption: `1400 MB/s`
=> perf: avoid double buffering in aead decryptor

src/packet/header.rs, src/packet/signature/types.rs
=> refactor: make InnerSignature private to avoid footguns

Cargo.lock, Cargo.toml, examples/decrypt_seipdv1.rs, examples/decrypt_seipdv2.rs, src/composed/message/reader.rs, src/composed/message/reader/compressed.rs, src/composed/message/reader/literal.rs, src/composed/message/reader/packet_body.rs, src/composed/message/reader/signed.rs, src/composed/message/reader/signed_one_pass.rs, src/composed/message/reader/sym_encrypted_protected.rs, src/composed/message/types.rs, src/crypto/aead/decryptor.rs, src/crypto/sym.rs, src/crypto/sym/decryptor.rs, src/crypto/sym/encryptor.rs, src/util.rs
This PR is a variant of the branch https://github.com/rpgp/rpgp/commits/perf-wip/, but without the GnuPG-AEAD functionality that is also present in `perf-wip`.
=> Performance improvements

Cargo.toml
=> chore: cleanup crate-type

src/composed/message/builder.rs, src/composed/message/parser.rs
An OpenPGP "Encrypted Message" may consist of just an "Encrypted Data", without any ESK:
https://www.rfc-editor.org/rfc/rfc9580.html#name-openpgp-messages
> ESK:    Public Key Encrypted Session Key Packet | Symmetric Key Encrypted Session Key Packet.
> ESK Sequence:    ESK | ESK Sequence, ESK.
> Encrypted Data:    Symmetrically Encrypted Data Packet | Symmetrically Encrypted and Integrity Protected Data Packet.
> Encrypted Message:    Encrypted Data | ESK Sequence, Encrypted Data.
Specifically, the last line (`Encrypted Message: Encrypted Data | ESK Sequence, Encrypted Data.`) allows an encrypted message to consist of just an encrypted data packet, without any session key packets.
This PR fixes parsing of encrypted messages without any ESK.
=> fix: Message::Encrypted may contain zero ESKs

src/composed/any.rs, src/composed/cleartext.rs, src/composed/message/builder.rs, src/composed/signature.rs, src/packet/signature/de.rs, src/packet/signature/types.rs, tests/pqc.rs, tests/security.rs, tests/signature_test.rs
=> feat: implement detached signature creation

Cargo.toml, README.md
Breaking out this side quest from https://github.com/rpgp/rpgp/pull/636#discussion_r2358052142
=> docs: move information about features to README
